import { useCallback,useEffect,useState } from 'react';
import { Link } from 'react-router-dom';
import { Activity,Box,Download,LayoutDashboard,Mail,RefreshCw,Search,ShieldCheck,Users } from 'lucide-react';
import { useAuth } from '../context/AuthContext.jsx';
import { api } from '../services/api.js';

const tabs=[['overview','Overview',LayoutDashboard],['users','Users',Users],['messages','Inquiries',Mail],['plugins','Marketplace',Box]];
const date=value=>value?new Intl.DateTimeFormat(undefined,{dateStyle:'medium'}).format(new Date(value)):'—';

export default function Admin(){
  const {user}=useAuth();
  const [tab,setTab]=useState('overview');
  const [data,setData]=useState(null);
  const [users,setUsers]=useState([]);
  const [messages,setMessages]=useState([]);
  const [query,setQuery]=useState('');
  const [loading,setLoading]=useState(false);
  const [error,setError]=useState('');
  const load=useCallback(async()=>{if(user?.role!=='admin')return;setLoading(true);setError('');try{const overview=await api.adminOverview();setData(overview);if(tab==='users')setUsers(await api.adminUsers(query));if(tab==='messages')setMessages(await api.adminMessages())}catch(e){setError(e.message)}finally{setLoading(false)}},[user,tab,query]);
  useEffect(()=>{load()},[load]);
  const updateUser=async(id,patch)=>{try{const next=await api.adminUpdateUser(id,patch);setUsers(rows=>rows.map(x=>x._id===id?next:x));await load()}catch(e){setError(e.message)}};
  const updateMessage=async(id,status)=>{try{const next=await api.adminUpdateMessage(id,status);setMessages(rows=>rows.map(x=>x._id===id?next:x));await load()}catch(e){setError(e.message)}};
  if(!user)return <section className="page-shell py-24 text-center"><p className="eyebrow">Admin console</p><h1 className="mt-4 text-4xl font-semibold">Authentication required.</h1><p className="mt-4 text-white/45">Sign in with your administrator account to continue.</p><Link to="/signin" className="mt-7 inline-flex rounded-xl bg-white px-5 py-3 text-sm font-semibold text-black">Sign in</Link></section>;
  if(user.role!=='admin')return <section className="page-shell py-24 text-center"><ShieldCheck className="mx-auto text-white/25" size={34}/><h1 className="mt-5 text-4xl font-semibold">Access denied.</h1><p className="mt-4 text-white/45">This area is restricted to Control Deck administrators.</p></section>;
  const stats=data?.stats||{};
  return <section className="page-shell py-12 sm:py-16"><div className="flex flex-col gap-5 border-b border-white/10 pb-8 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.18em] text-emerald-200"><span className="h-2 w-2 rounded-full bg-emerald-400"/>Live operations</div><h1 className="mt-4 text-4xl font-semibold tracking-[-.04em] sm:text-5xl">Control Deck Admin</h1><p className="mt-3 text-sm text-white/45">Manage customers, inquiries and marketplace operations from one protected workspace.</p></div><button onClick={load} disabled={loading} className="inline-flex w-fit items-center gap-2 rounded-xl border border-white/10 bg-white/[.035] px-4 py-2.5 text-sm text-white/60 transition hover:bg-white/[.07] hover:text-white disabled:opacity-50"><RefreshCw size={15} className={loading?'animate-spin':''}/>Refresh data</button></div>
    <div className="mt-7 grid gap-7 lg:grid-cols-[220px_minmax(0,1fr)]"><aside className="h-fit rounded-2xl border border-white/10 bg-white/[.025] p-3 lg:sticky lg:top-24"><p className="px-3 py-2 text-[10px] font-semibold uppercase tracking-[.18em] text-white/30">Workspace</p>{tabs.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`mt-1 flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm transition ${tab===id?'bg-white/[.08] text-white':'text-white/45 hover:bg-white/[.04] hover:text-white'}`}><Icon size={16}/>{label}{id==='messages'&&stats.messages>0&&<span className="ml-auto rounded-full bg-violet-500 px-2 py-0.5 text-[10px] text-white">{stats.messages}</span>}</button>)}</aside>
      <main className="min-w-0">{error&&<p role="alert" className="mb-5 rounded-xl border border-red-400/20 bg-red-400/[.06] p-4 text-sm text-red-200">{error}</p>}
        {tab==='overview'&&<><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[[Users,'Customers',stats.users],[Activity,'Active accounts',stats.activeUsers],[Box,'Owned plugins',stats.entitlements],[Download,'Downloads',stats.downloads],[Mail,'New inquiries',stats.messages],[ShieldCheck,'Verified plugins',stats.plugins]].map(([Icon,name,value])=><div className="rounded-2xl border border-white/10 bg-white/[.025] p-5" key={name}><div className="flex items-center justify-between"><p className="text-sm text-white/42">{name}</p><Icon size={17} className="text-violet-300"/></div><p className="mt-4 text-3xl font-semibold">{value??'—'}</p></div>)}</div><div className="mt-7 grid gap-6 xl:grid-cols-2"><Panel title="Recent customers">{data?.recentUsers?.map(x=><div key={x._id} className="flex items-center justify-between gap-4 border-t border-white/8 py-3 first:border-0"><div><p className="text-sm font-medium">{x.name}</p><p className="mt-1 text-xs text-white/35">{x.email}</p></div><span className="text-xs text-white/35">{date(x.createdAt)}</span></div>)}</Panel><Panel title="Recent inquiries">{data?.recentMessages?.map(x=><div key={x._id} className="border-t border-white/8 py-3 first:border-0"><div className="flex justify-between gap-4"><p className="text-sm font-medium">{x.subject}</p><Status value={x.status}/></div><p className="mt-1 text-xs text-white/35">{x.name} · {x.email}</p></div>)}</Panel></div></>}
        {tab==='users'&&<><div className="mb-5 flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-white/30" size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name or email" className="w-full rounded-xl border border-white/10 bg-white/[.025] py-3 pl-11 pr-4 outline-none focus:border-violet-400/40"/></label></div><div className="overflow-x-auto rounded-2xl border border-white/10"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-white/[.035] text-xs uppercase tracking-wider text-white/35"><tr><th className="p-4">Customer</th><th className="p-4">Role</th><th className="p-4">Status</th><th className="p-4">Joined</th></tr></thead><tbody>{users.map(x=><tr key={x._id} className="border-t border-white/8"><td className="p-4"><p className="font-medium">{x.name}</p><p className="mt-1 text-xs text-white/35">{x.email}</p></td><td className="p-4"><select value={x.role} onChange={e=>updateUser(x._id,{role:e.target.value})} className="rounded-lg border border-white/10 bg-[#0d1016] px-3 py-2 text-white/70">{['user','creator','developer','admin'].map(role=><option key={role}>{role}</option>)}</select></td><td className="p-4"><button onClick={()=>updateUser(x._id,{active:x.active===false})} className={`rounded-full border px-3 py-1.5 text-xs ${x.active===false?'border-red-400/20 text-red-200':'border-emerald-400/20 text-emerald-200'}`}>{x.active===false?'Disabled':'Active'}</button></td><td className="p-4 text-white/40">{date(x.createdAt)}</td></tr>)}</tbody></table></div></>}
        {tab==='messages'&&<div className="space-y-3">{messages.map(x=><article key={x._id} className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-3"><h3 className="font-semibold">{x.subject}</h3><Status value={x.status}/></div><p className="mt-2 text-xs text-white/35">{x.name} · {x.email} · {date(x.createdAt)}</p><p className="mt-4 max-w-3xl text-sm leading-6 text-white/55">{x.message}</p></div><select value={x.status} onChange={e=>updateMessage(x._id,e.target.value)} className="rounded-lg border border-white/10 bg-[#0d1016] px-3 py-2 text-sm text-white/70"><option value="new">New</option><option value="in_progress">In progress</option><option value="closed">Closed</option></select></div></article>)}</div>}
        {tab==='plugins'&&<div className="grid gap-4 sm:grid-cols-2">{data?.plugins?.map(x=><article key={x.id} className="rounded-2xl border border-white/10 bg-white/[.025] p-6"><div className="flex items-center justify-between"><div className="grid h-12 w-12 place-items-center rounded-xl bg-white"><img src="/marketplace-previews/obs-logo.svg" className="h-9 w-9" alt=""/></div><span className="rounded-full border border-emerald-400/20 px-3 py-1 text-xs text-emerald-200">Published</span></div><h3 className="mt-6 text-xl font-semibold">{x.name}</h3><p className="mt-2 text-sm text-white/40">{x.id}</p><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-xl border border-white/8 p-3"><p className="text-xs text-white/35">Version</p><p className="mt-1 font-semibold">{x.version}</p></div><div className="rounded-xl border border-white/8 p-3"><p className="text-xs text-white/35">Actions</p><p className="mt-1 font-semibold">{x.actions}</p></div></div></article>)}</div>}
      </main></div></section>;
}

function Panel({title,children}){return <section className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><h2 className="font-semibold">{title}</h2><div className="mt-4">{children}</div></section>}
function Status({value}){const label=value==='in_progress'?'In progress':value?.[0]?.toUpperCase()+value?.slice(1);return <span className={`rounded-full border px-2.5 py-1 text-[10px] ${value==='new'?'border-violet-400/25 text-violet-200':value==='closed'?'border-white/10 text-white/35':'border-amber-400/20 text-amber-200'}`}>{label}</span>}
