import { Link, useOutletContext, useParams } from 'react-router-dom';
import { ArrowLeft, Check, ChevronRight, Download, LockKeyhole, ShoppingBag, ShieldCheck } from 'lucide-react';
import Rating from '../components/Rating.jsx';
import MarketplaceCard from '../components/MarketplaceCard.jsx';
import MarketplacePreviewArt from '../components/MarketplacePreviewArt.jsx';
import { marketplace } from '../data/marketplaceData.js';

export default function MarketplaceItem(){
  const {slug}=useParams();
  const store=useOutletContext();
  const item=marketplace.find(x=>x.slug===slug);
  if(!item) return <div className="grid min-h-[420px] place-items-center rounded-3xl border border-white/10 bg-white/[.025] text-center"><div><p className="eyebrow">Marketplace</p><h2 className="mt-4 text-2xl font-semibold">Marketplace item not found.</h2><Link to="/marketplace" className="mt-6 inline-flex rounded-xl bg-white px-5 py-3 text-sm font-semibold text-black">Back to Marketplace</Link></div></div>;
  const Icon=item.icon;
  const owned=store.librarySet.has(item.slug);
  const inCart=store.cartSet.has(item.slug);
  const related=marketplace.filter(x=>x.category===item.category&&x.slug!==item.slug).slice(0,3);
  return <>
    <div className="mb-7 flex flex-wrap items-center gap-2 border-b border-white/10 pb-5 text-sm text-white/40"><Link to="/marketplace" className="inline-flex items-center gap-2 transition hover:text-white"><ArrowLeft size={15}/>Marketplace</Link><ChevronRight size={13}/><Link to={`/marketplace/control-deck?tab=${item.category}`} className="transition hover:text-white">{item.category}</Link><ChevronRight size={13}/><span className="text-white/65">{item.name}</span></div>
    <div className="mb-8"><p className="eyebrow">{item.type}</p><h1 className="mt-3 text-3xl font-semibold tracking-[-.035em] sm:text-4xl">{item.name}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/45">{item.tagline}</p></div>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1.25fr)_340px]">
      <div className="space-y-6">
        <div className="rounded-3xl border border-white/10 bg-white/[.025] p-3 sm:p-5"><MarketplacePreviewArt item={item} className="w-full"><div className="absolute bottom-5 right-5 grid h-16 w-16 place-items-center rounded-2xl border border-white/10 bg-black/45 shadow-panel backdrop-blur-sm"><Icon className="h-7 w-7 text-violet-200"/></div></MarketplacePreviewArt></div>
        <div><h2 className="text-xl font-semibold">Gallery</h2><div className="mt-4 grid gap-4 sm:grid-cols-3">{item.gallery.map((x,i)=><div key={x} className="aspect-[16/10] rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="flex h-full items-end rounded-xl border border-white/10 bg-white/[.02] p-4"><div><span className="text-[10px] uppercase tracking-widest text-white/30">Preview {i+1}</span><p className="mt-1 text-sm text-white/65">{x}</p></div></div></div>)}</div></div>
        <article className="rounded-3xl border border-white/10 bg-white/[.025] p-6 sm:p-8"><p className="eyebrow">About this item</p><p className="mt-5 max-w-3xl text-base leading-8 text-white/60">{item.description}</p><h2 className="mt-9 text-lg font-semibold">What’s included</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{item.includes.map(x=><div key={x} className="rounded-xl border border-white/10 bg-white/[.02] p-4 text-sm text-white/65">{x}</div>)}</div>{item.permissions?.length>0&&<><h2 className="mt-9 text-lg font-semibold">Permissions</h2><div className="mt-4 grid gap-3">{item.permissions.map(x=><div key={x} className="flex items-start gap-3 rounded-xl border border-white/10 bg-white/[.02] p-4 text-sm text-white/60"><LockKeyhole size={16} className="mt-0.5 shrink-0 text-violet-300"/>{x}</div>)}</div></>}</article>
      </div>
      <aside className="h-fit rounded-3xl border border-white/10 bg-white/[.025] p-6 xl:sticky xl:top-24"><div className="flex items-start justify-between gap-4"><div><p className="text-sm text-white/40">Created by</p><Link to={`/marketplace/maker/${item.creatorSlug}`} className="mt-1 block font-semibold transition hover:text-violet-200">{item.creator}</Link></div><strong>{item.price}</strong></div><div className="mt-6 flex items-center justify-between border-y border-white/10 py-4"><Rating value={item.rating}/><span className="text-xs text-white/40">{item.downloads} downloads</span></div><div className="mt-5 flex gap-3 text-xs leading-5 text-white/45"><ShieldCheck size={17} className="mt-0.5 shrink-0 text-emerald-300"/><p>Review product details and permissions before adding an item to your Control Deck library.</p></div><div className="mt-6">{owned?(item.category==='Plugins'?<button onClick={async()=>{try{await store.install(item.slug)}catch(e){store.setMessage(e.message)}}} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-semibold text-black transition hover:bg-white/90"><Download size={16}/>Install in Control Deck</button>:<div className="rounded-xl border border-emerald-400/20 bg-emerald-400/[.06] px-4 py-3 text-center text-sm font-medium text-emerald-200"><Check size={15} className="mr-2 inline"/>Owned in your library</div>):item.free?<button onClick={()=>store.addFree(item.slug)} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-semibold text-black transition hover:bg-white/90"><Download size={16}/>Get for free</button>:<button onClick={()=>store.toggleCart(item.slug)} className={`inline-flex w-full items-center justify-center gap-2 rounded-xl px-4 py-3 text-sm font-semibold transition ${inCart?'border border-violet-400/30 bg-violet-400/10 text-violet-200':'bg-white text-black hover:bg-white/90'}`}><ShoppingBag size={16}/>{inCart?'Remove from cart':'Add to cart · '+item.price}</button>}</div>{store.message&&<p className="mt-3 rounded-xl border border-white/10 bg-white/[.03] px-3 py-2 text-xs leading-5 text-white/50">{store.message}</p>}{owned&&<Link to="/marketplace/library" className="mt-3 block text-center text-xs text-white/45 transition hover:text-white">Open your library</Link>}{inCart&&<Link to="/marketplace/cart" className="mt-3 block text-center text-xs text-white/45 transition hover:text-white">View cart</Link>}</aside>
    </div>
    {related.length>0&&<section className="mt-16"><h2 className="text-2xl font-semibold tracking-[-.02em]">More {item.category.toLowerCase()}</h2><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{related.map(x=><MarketplaceCard key={x.slug} item={x} librarySet={store.librarySet} cartSet={store.cartSet} onGet={store.addFree} onCart={store.toggleCart}/>)}</div></section>}
  </>
}
