import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Check } from 'lucide-react';
import AuthShell from '../components/AuthShell.jsx';
import { useAuth } from '../context/AuthContext.jsx';

export default function SignUp(){
  const {register}=useAuth();
  const navigate=useNavigate();
  const [form,setForm]=useState({name:'',email:'',password:'',confirmPassword:''});
  const [accepted,setAccepted]=useState(false);
  const [error,setError]=useState('');
  const [loading,setLoading]=useState(false);
  const submit=async(e)=>{e.preventDefault();setError('');if(form.password!==form.confirmPassword)return setError('Passwords do not match.');if(!accepted)return setError('Please accept the Terms and Privacy Policy.');setLoading(true);try{await register({name:form.name,email:form.email,password:form.password});navigate('/marketplace/library')}catch(err){setError(err.message)}finally{setLoading(false)}};
  const inputClass="w-full rounded-xl border border-white/10 bg-black/25 px-4 py-3 outline-none transition focus:border-violet-400/60 focus:ring-4 focus:ring-violet-400/[.08]";
  return <AuthShell eyebrow="Get started" title="Create your account." description="Build your library and install verified Control Deck plugins."><form onSubmit={submit}><div className="grid gap-4 sm:grid-cols-2"><label><span className="mb-2 block text-sm text-white/60">Name</span><input type="text" autoComplete="name" minLength="2" maxLength="80" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className={inputClass}/></label><label><span className="mb-2 block text-sm text-white/60">Email</span><input type="email" autoComplete="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})} className={inputClass}/></label></div><label className="mt-4 block"><span className="mb-2 block text-sm text-white/60">Password</span><input type="password" autoComplete="new-password" minLength="12" maxLength="128" required value={form.password} onChange={e=>setForm({...form,password:e.target.value})} className={inputClass}/><span className="mt-2 block text-xs text-white/35">Use 12–128 characters.</span></label><label className="mt-4 block"><span className="mb-2 block text-sm text-white/60">Confirm password</span><input type="password" autoComplete="new-password" minLength="12" maxLength="128" required value={form.confirmPassword} onChange={e=>setForm({...form,confirmPassword:e.target.value})} className={inputClass}/></label><label className="mt-5 flex cursor-pointer items-start gap-3 text-sm leading-6 text-white/50"><span className={`mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded border ${accepted?'border-violet-400 bg-violet-500 text-white':'border-white/15 bg-black/20'}`}>{accepted&&<Check size={13}/>}</span><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)} className="sr-only"/><span>I agree to the <Link to="/terms" className="text-violet-200 hover:text-violet-100">Terms</Link> and <Link to="/privacy" className="text-violet-200 hover:text-violet-100">Privacy Policy</Link>.</span></label>{error&&<p role="alert" className="mt-4 rounded-xl border border-red-400/20 bg-red-400/[.06] px-4 py-3 text-sm text-red-200">{error}</p>}<button disabled={loading} className="mt-6 w-full rounded-xl bg-white py-3.5 text-sm font-semibold text-black transition hover:bg-white/90 disabled:opacity-60">{loading?'Creating account…':'Create Control Deck account'}</button><p className="mt-6 text-center text-sm text-white/45">Already registered? <Link to="/signin" className="font-medium text-violet-200 hover:text-violet-100">Sign in</Link></p></form></AuthShell>
}
