import { Link, useParams } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';
import PageHero from '../components/PageHero.jsx';
import Button from '../components/Button.jsx';

const articles={
'getting-started':{title:'Getting started with Control Deck',copy:'Set up your first profile and understand the basic Control Deck workflow.',steps:['Install the current supported Control Deck build from the Download page.','Create a profile for one task, app or workflow you use often.','Add a small set of actions first, then organize extra controls into folders as the profile grows.']},
'profiles':{title:'Creating and switching profiles',copy:'Keep different workflows focused by separating them into profiles.',steps:['Use clear profile names such as Streaming, Editing, Gaming or Work.','Keep high-frequency actions on the first page and secondary actions inside folders.','Switch profiles when your context changes instead of overcrowding one universal layout.']},
'plugins':{title:'Installing plugins safely',copy:'Review marketplace information before adding plugin capabilities.',steps:['Open the plugin item page and review its purpose, creator and included capabilities.','Use plugins from sources you trust and review requested permissions when the production permission system is available.','Keep plugins updated and remove anything you no longer use.']},
'marketplace-downloads':{title:'Managing marketplace downloads',copy:'Understand how marketplace items are organized and prepared for future account libraries.',steps:['Use the Marketplace tabs to narrow the catalog by product type.','Open an item detail page before downloading so you can review what is included.','Account entitlements and personal libraries are represented in the architecture and can be connected to the production API later.']},
'connections':{title:'Troubleshooting application connections',copy:'Use a simple checklist when an integration does not respond.',steps:['Confirm the target application is installed and running.','Check that the relevant Control Deck plugin or integration is enabled.','Restart the application connection and verify that the action is mapped to the correct profile control.']},
'accessibility':{title:'Keyboard and accessibility controls',copy:'Control Deck’s web experience is designed around usable focus states and reduced motion.',steps:['Use Tab and Shift+Tab to move through interactive website controls.','Visible focus states help show the currently selected element.','If reduced motion is enabled at operating-system level, supported website animations are reduced automatically.']}
};

export default function SupportArticle(){const {slug}=useParams();const item=articles[slug];if(!item)return <PageHero eyebrow="Support" title="Support article not found." description="Browse the support center for another topic."><Button to="/support">Support Center</Button></PageHero>;return <><section className="page-shell pt-14 sm:pt-20"><Link to="/support" className="inline-flex items-center gap-2 text-sm text-white/45 hover:text-white"><ArrowLeft size={15}/>Back to Support</Link></section><PageHero eyebrow="Support guide" title={item.title} description={item.copy}/><section className="page-shell pb-24"><div className="surface mx-auto max-w-4xl rounded-3xl p-6 sm:p-10"><ol className="space-y-5">{item.steps.map((step,i)=><li key={step} className="flex gap-4 text-sm leading-7 text-white/60"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full border border-white/10 bg-white/[.04] text-xs text-white/70">{i+1}</span><span>{step}</span></li>)}</ol></div></section></>}
