import { useState } from 'react';
import { motion } from 'framer-motion';
import { Radio, Gamepad2, BriefcaseBusiness, Clapperboard, Mic, Camera, MessageSquare, Circle, Globe, Mail, CalendarDays, Music2, Focus, Github, Terminal, Image, Upload, Download } from 'lucide-react';
import AnimatedSection from '../components/AnimatedSection.jsx';
const profiles={
 Streaming:[['Start Stream',Radio],['Mic',Mic],['Camera',Camera],['Chat',MessageSquare],['Record',Circle],['Switch Scene',Clapperboard]],
 Gaming:[['Launch Game',Gamepad2],['Discord',MessageSquare],['Screenshot',Camera],['Clip',Clapperboard],['Mute',Mic],['Performance',Radio]],
 Productivity:[['Browser',Globe],['Email',Mail],['Calendar',CalendarDays],['Music',Music2],['Focus Mode',Focus],['Terminal',Terminal]],
 Creator:[['Premiere',Clapperboard],['Photoshop',Image],['GitHub',Github],['After Effects',Clapperboard],['Upload',Upload],['Export',Download]],
};
export default function ProductShowcase(){const [active,setActive]=useState('Streaming');return <AnimatedSection className="page-shell py-24"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="eyebrow">One deck. Every context.</p><h2 className="section-title mt-4">Profiles that change with the way you work.</h2><p className="mt-5 max-w-xl text-lg leading-8 text-white/55">Build focused control surfaces for streaming, gaming, creative work and everyday productivity. Switch context without rebuilding your workflow.</p><div className="mt-8 flex flex-wrap gap-2">{Object.keys(profiles).map(p=><button key={p} onClick={()=>setActive(p)} className={`rounded-full px-4 py-2 text-sm transition ${active===p?'bg-white text-black':'border border-white/10 bg-white/5 text-white/60 hover:text-white'}`}>{p}</button>)}</div></div><div className="surface rounded-[32px] p-4 sm:p-6"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs text-white/40">ACTIVE PROFILE</p><p className="mt-1 font-semibold">{active}</p></div><span className="rounded-full bg-emerald-400/10 px-3 py-1 text-xs text-emerald-300">Connected</span></div><motion.div key={active} initial={{opacity:0,scale:.98}} animate={{opacity:1,scale:1}} className="grid grid-cols-2 gap-3 sm:grid-cols-3">{profiles[active].map(([name,Icon],i)=><motion.button whileHover={{y:-3}} key={name} className="group min-h-28 rounded-2xl border border-white/10 bg-[#11151d] p-4 text-left hover:border-violet-400/35"><Icon className="h-5 w-5 text-violet-300"/><span className="mt-8 block text-sm font-medium">{name}</span><span className="text-[11px] text-white/35">Action {String(i+1).padStart(2,'0')}</span></motion.button>)}</motion.div></div></div></AnimatedSection>}
